### ISSUE TITLE
Unable to install the drivers due to the below error

### ISSUE THREAD

**Issue by rajasubudhi1988** [dlenroc/appium-roku-driver#56]
**i have used the drivers before, after few days uninstalled and trying to install it back,ci am seeing the below error.** 

raja.subudhi@YFYTXJ24VR ~ % appium driver install --source=npm @headspinio/appium-roku-driver
WARN Appium Appium encountered 11 warnings while validating drivers found in manifest /Users/raja.subudhi/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "YouiEngine" has 1 potential problem: 
WARN Appium   - Driver "YouiEngine" (package `appium-youiengine-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-youiengine-driver` to add a peer dependency on `^appium@2.0.0-beta.46`.
✖ Installing '@headspinio/appium-roku-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock @headspinio/appium-roku-driver --json' failed with code 1.

STDOUT:

STDERR:
npm WARN deprecated @types/puppeteer@7.0.4: This is a stub types definition. puppeteer provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @dabh/colors@1.4.0: @dabh/colors has been renamed to @colors/colors. Please update your package.json.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver
npm ERR! command failed
npm ERR! command sh -c -- node install-npm.js
npm ERR! [21:30:43] Error installing Chromedriver: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR! [21:30:43] Error: Cannot find module '@appium/support'
npm ERR! Require stack:
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium/support.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js
npm ERR! - /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR! [21:30:43] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c -- node install-npm.js\n[21:30:43] Error installing Chromedriver: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n[21:30:43] Error: Cannot find module '@appium/support'\nRequire stack:\n- /Users/raja.subudhi/.appium/node_modules/appium/support.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/build/lib/install.js\n- /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/install-npm.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:841:27)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium/support.js:13:18)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n    at Module.require (node:internal/modules/cjs/loader:1061:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver/node_modules/appium-chromedriver/lib/install.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:878:12)\n[21:30:43] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raja.subudhi/.npm/_logs/2022-11-26T15_59_01_195Z-debug-0.log

**Comment by rajasubudhi1988** [comment]
@dlenroc please help to resolve this issue and not sure prints for "appium-tizen-tv-driver/"

**Comment by dlenroc** [comment]
Hey @rajasubudhi1988 your problem has nothing to do with the roku driver from this repository.

1. You are trying to install [@headspinio/appium-roku-driver](https://github.com/headspinio/appium-roku-driver) instead of [@dlenroc/appium-roku-driver](https://www.npmjs.com/package/@dlenroc/appium-roku-driver).
2. The error says that the installation failed due to `appium-tizen-tv-driver` which is also supported by headpin (most likely it is not compatible with the version of Appium 2 you are using, so appium 2 loading phase fails).

-------

PS: if you intend to install this driver, I suggest:
- Install Node.js 16/18 LTS and check that it's installed via `node --version`.
- Install/Upgrade Appium 2 via `npm install -g appium@next` or use `npx appium@next`. 
- Remove possible broken drivers and configurations `rm -rf ~/.appium`.
- Install driver `npx appium@next driver install --source npm @dlenroc/appium-roku-driver`.
- Start Appium 2 server without or with arguments you may need.
   ```shell
   npx appium@next server --use-drivers roku -dc "{ \"appium:ip\": \"<ip>\", \"appium:username\": \"<username>\", \"appium:password\": \"<password>\" }"
   ```

**Comment by rajasubudhi1988** [comment]
Hi @dlenroc ,
My Bad. I used this driver too [@dlenroc/appium-roku-driver](https://www.npmjs.com/package/@dlenroc/appium-roku-driver) and it was working for me earlier . Unfortunately very recently i tried with appium-tizen-tv-driver and all break as above ,the logs shared at the time when i was tried headspin driver from roku with an assumption may this resolve the issue.

Thanks for the suggestion i will try the above step as mentioned  by you.

**Comment by rajasubudhi1988** [comment]
@dlenroc ,We can close the issue, its working perfectly fine now in my setup.
