### ISSUE TITLE
Appium Command installApp doesn't work on Windows

### ISSUE THREAD

**Issue by quidow** [dlenroc/appium-roku-driver#66]
The rest of commands work, so I believe that this issue is related to the Windows path format.
The same command works perfectly on Linux/MacOS.
![image_2023_11_28T09_07_36_418Z](https://github.com/dlenroc/appium-roku-driver/assets/60624018/c179c001-a7ef-49df-95b9-390963202d62)

**Comment by dlenroc** [comment]
May I ask if the same version of Node.js was used on Windows and if latest version of driver was used, and if so, please try the code below ?

```
const fs = require('node:fs');
const { DeveloperServer } = require('@dlenroc/roku-developer-server');

const developerServer = new DeveloperServer({
  address: 'http://<device-ip>',
  username: 'rokudev',
  password: '<device-password>',
});

developerServer.install(fs.readFileSync('app.zip'))
  .then(() => { console.log('Installed'); })
  .catch((error) => { console.error(error); });
```

Also, to ensure there are no compilation issues, please connect to BrightScript console before attempting to install the app.

```
telnet <device-ip> 8085
```

**Comment by dlenroc** [comment]
Hello @quidow, if the issue isn't resolved, consider trying GH-68 which have more detailed error message, including information about compilation errors.

**Comment by quidow** [comment]
Node v20.8.0
Seems like a weird reason to me, since everything work perfectly with the same device and on the same computer, but via WSL...

![2023-12-22_17-44](https://github.com/dlenroc/appium-roku-driver/assets/60624018/989a9de7-8d13-458d-b080-3269327063e2)

**Comment by dlenroc** [comment]
Thanks, @quidow! The first part may be related to the need to regenerate the developer key (I have not seen this message before), and the second part is the issue I need to address. Now, I have everything I need to fix it. Great, thanks!

**Comment by dlenroc** [comment]
Windows support has been added in the [@dlenroc/appium-roku-driver@0.10.0](https://www.npmjs.com/package/@dlenroc/appium-roku-driver/v/0.10.0) release.
