### ISSUE TITLE
Focus switch/animation complete after pressing a button

### ISSUE THREAD

**Issue by quidow** [dlenroc/appium-roku-driver#84]
Hello @dlenroc,
Is it possible to track somehow that the focus was moved after pressing a button? At this moment I use 0.5 sec sleep after each press to make sure the animation is complete and the focus is moved, but maybe there is a smarter way to do it instead of using this sleep.

**Comment by dlenroc** [comment]
I use Action API to focus/select elements via a project step.
```ts
await browser
  .action('pointer')
  .move({ origin: element, duration: 5000 })
  .perform();
```

Alternatively, you can use knowledge about the current element in focus to create more complex steps.
```ts
// 1. Identify focused element
const previousActiveElement = await $(await browser.getActiveElement());

// 2. Press a button from the remote
await device.driver
    .action('key')
    .down(Key.ArrowDown)
    .up(Key.ArrowDown)
    .perform();

// 3. Wait focused element to change
await browser.waitUntil(
  async () => {
    const activeElement = await $(await browser.getActiveElement());
    return previousActiveElement.elementId !== activeElement.elementId;
  },
  {
    interval: 100,
    timeout: 5000,
  }
);
```

PS: 
- Samples use [WebdriverIO](https://webdriver.io/) api, but similar methods are available for other languages/libraries. Please refer to their documentation for the exact names.
- If there is interest, I may enable GitHub discussion for this repository for questions and ideas.
